version: "2"
exclude_patterns:
  - "**/src/main/java/chapi/ast/antlr/"
  - "**/resources/**"
  - "tests/"
#
#checks:
#  identical-code:
#    config:
#      threshold: 25
#  similar-code:
#    config:
#      threshold: 50

plugins:
  duplication:
    enabled: true
    config:
      languages:
        kotlin:
          exclude_patterns:
            - "**/*Analyser.kt"
            - "**/*Test.kt"
